### ISSUE TITLE
Superpixel Candidates

### ISSUE THREAD

**Issue by photopea** [nchucvml/USEAQ#1]
Hi, I have a question about the stage, where you pick 1 to S superpixel candidates from a quantized rectangular sub-region (III. B.).

You are creating candidates according to the quantized color. Do you create only compact (continuous) candidates? If several pixels have the same color, but are not connected, are they inside one candidate?

If you create only continuous candidates, how do you assign unassigned pixels to the "closest" candidate? I believe it is not trivial, if you want to preserve the continuity.

If candidates are not continuous, are superpixels (by your definition) continuous? I can not see, at what point you ensure the continuity of them.

**Comment by nchucvml** [comment]
For each region $R_i$, the pixels of a quantized color in $R_i$ yield a superpixel candidate if the number of these pixels is larger than $\tau$. The candidates are not continuous and are decided by the area sizes. That is the reason why we need to perform MAP-Based Pixel-Superpixel Reassignment in Sec. III (c) to assign pixels to superpixels.
